version: "3"
services:
  web:
    image: node:9.11.1-alpine
    ports:
    - "8080:3000"
    volumes:
      - "./web:/srv/app"
    environment:
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    working_dir: /srv/app
    entrypoint: node --experimental-modules .

  database:
    image: mongo:3.0.15-wheezy
    volumes:
      - "./database:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
