version: "3"
services:
  database:
    image: mysql:5.7.22
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE

  web:
    build: ./web
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3000:3000"
    volumes:
      - ./web:/srv/app
      - /srv/app/node_modules
    entrypoint: npm start
