version: "2"
services:
  database:
    image: mysql:5.7.22
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - database.env

  web:
    build: ./web
    ports:
      - "3000:3000"
    env_file:
      - database.env
    volumes:
      - ./web:/srv/app
      - /srv/app/node_modules
    entrypoint: node .

volumes:
  mysql_data:
